<?php
date_default_timezone_set('Asia/Seoul');
require_once './PHPExcel-1.8/Classes/PHPExcel.php';

//첫번째 변수 - 시작날짜, 두번째 변수- 종료날짜, 세번째 변수 - 지역 이름(GURO 고정)
$STARTDATE=$_GET['start_date'];
$ENDDATE=$_GET['end_date'];
$STAT=$_GET['stat'];

if($STAT == "GURO")
    {

 // 엑셀의 전체적인 양식 설정
$objPHPExcel = new PHPExcel();

$sheet = $objPHPExcel->getActiveSheet();
$sheetIndex = $objPHPExcel->setActiveSheetIndex(0);

$sheetIndex->setCellValue('A1','구로 호처리 트래픽 정보');
$sheetIndex->mergeCells('A1:D1');
$sheetIndex->getStyle('A1')->getFont()->setSize(20)->setBold(true);
$sheetIndex->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);


$sheetIndex->setCellValue('A2','SYSTEM');
$sheetIndex->setCellValue('B2','CAPACITY');
$sheetIndex->setCellValue('C2','MAX Gbps');
$sheetIndex->setCellValue('D2','MAX SESSION');
$sheetIndex->setCellValue('E2','비고');

$sheetIndex->setCellValue('E3','로밍');
$sheetIndex->setCellValue('E4','M2M/IoT');
$sheetIndex->setCellValue('E5','IPv6');
$sheetIndex->setCellValue('E6','EMTC');
$sheetIndex->setCellValue('E7','IPv4');
$sheetIndex->setCellValue('E8','IPv4');
$sheetIndex->setCellValue('E9','VoLTE');
$sheetIndex->setCellValue('E10','IPv4');
$sheetIndex->setCellValue('E11','IPv6');
$sheetIndex->setCellValue('E12','IPv6');
$sheetIndex->setCellValue('E13','IPv6');
$sheetIndex->setCellValue('E14','IPv6');
$sheetIndex->setCellValue('E15','3G Alwayson');
$sheetIndex->setCellValue('E21','DATA');
$sheetIndex->setCellValue('E22','DATA');
$sheetIndex->setCellValue('E23','DATA');
$sheetIndex->setCellValue('E24','DATA');
$sheetIndex->setCellValue('E25','DATA');
$sheetIndex->setCellValue('E26','DATA');
$sheetIndex->setCellValue('E27','DATA');
$sheetIndex->setCellValue('E28','DATA');
$sheetIndex->setCellValue('E29','DATA');
$sheetIndex->setCellValue('E30','DATA');
$sheetIndex->setCellValue('E31','DATA');
$sheetIndex->setCellValue('E32','DATA');
$sheetIndex->setCellValue('E33','IMS');
$sheetIndex->setCellValue('E34','IMS');
$sheetIndex->setCellValue('E35','IMS');
$sheetIndex->setCellValue('E36','IMS');
$sheetIndex->setCellValue('E37','IMS');
$sheetIndex->setCellValue('E38','IMS');
$sheetIndex->setCellValue('E39','IMS');
$sheetIndex->setCellValue('E40','IMS');

// MYSQL 에 접속해서 시작날짜, 종료날짜 사이의 원하는 DATA 파싱(트래픽, 세션)
$PGW01_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW01_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW03_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW03_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW04_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW04_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW05_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW05_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW11_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW11_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW12_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW12_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW13_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW13_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW15_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW15_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW16_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW16_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW17_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW17_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW18_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW18_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW19_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW19_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$PGW20_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_PGW20_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SMF02_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SMF02_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

$PGW01_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW01_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW03_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW03_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW04_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW04_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW05_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW05_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW11_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW11_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW12_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW12_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW13_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF+SESSSTAT_BEARACT_DED) from ".$STAT."_PGW13_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW15_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW15_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW16_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW16_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW17_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW17_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW18_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW18_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW19_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW19_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$PGW20_SESSION="SELECT MAX(SESSSTAT_BEARACT_DEF) from ".$STAT."_PGW20_PGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

#$SGW01_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW01_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
#$SGW02_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW02_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SGW11_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW11_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SGW12_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW12_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SGW13_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW13_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SGW14_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW14_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$SGW15_TRAFFIC="SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(UTIL_RX_5MIN_MBPS) AS RX,SUM(UTIL_TX_5MIN_MBPS) AS TX from ".$STAT."_SGW15_PortStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

#$SGW01_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW01_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
#$SGW02_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW02_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$SGW11_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW11_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$SGW12_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW12_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$SGW13_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW13_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$SGW14_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW14_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$SGW15_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SGW15_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

$SMF02_SESSION="SELECT MAX(SESSSTAT_TOTCUR_BEARERS) from ".$STAT."_SMF02_SGWAttachStat where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

$UPF02_01_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_02_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_03_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_04_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_05_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_06_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_07_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_08_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_09_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_10_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_11_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF02_12_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF02_PortUtilStat where SYSTEM = 'GURO_UPF02-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

$UPF11_01_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_02_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_03_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_04_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_05_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_06_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_07_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF11_08_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF11_PortUtilStat where SYSTEM = 'GURO_UPF11-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

$UPF12_01_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_02_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_03_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_04_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_05_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_06_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_07_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_08_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_09_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_10_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_11_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF12_12_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF12_PortUtilStat where SYSTEM = 'GURO_UPF12-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

$UPF13_01_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_02_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_03_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_04_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_05_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_06_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_07_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_08_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_09_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_10_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_11_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";
$UPF13_12_TRAFFIC = "SELECT SYSTEM,MAX(subquery1.RX) FROM (SELECT SYSTEM,DATETIME,SUM(RX_AVG_5MIN_MBPS) AS RX,SUM(TX_AVG_5MIN_MBPS) AS TX from ".$STAT."_UPF13_PortUtilStat where SYSTEM = 'GURO_UPF13-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";


$UPF02_01_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_02_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_03_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_04_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_05_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_06_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_07_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_08_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_09_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_10_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_11_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF02_12_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF02_SxPeerStat where SYSTEM='GURO_UPF02-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

$UPF11_01_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_02_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_03_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_04_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_05_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_06_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_07_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF11_08_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF11_SxPeerStat where SYSTEM='GURO_UPF11-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

$UPF12_01_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_02_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_03_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_04_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_05_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_06_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_07_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_08_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_09_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_10_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_11_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF12_12_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF12_SxPeerStat where SYSTEM='GURO_UPF12-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";

$UPF13_01_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-01' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_02_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-02' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_03_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-03' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_04_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-04' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_05_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-05' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_06_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-06' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_07_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-07' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_08_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-08' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_09_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-09' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_10_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-10' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_11_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-11' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";
$UPF13_12_SESSION = "SELECT MAX(CURRENT_SESSION) from ".$STAT."_UPF13_SxPeerStat where SYSTEM='GURO_UPF13-12' AND DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."';";


$MME1_SESSION = "SELECT SYSTEM,MAX(subquery1.SESS) FROM (SELECT SYSTEM,SUM(PEAK_TOTAL) AS SESS from `".$STAT."_A-MME2_MS|EMSC` where DATETIME BETWEEN '".$STARTDATE."' AND '".$ENDDATE."' GROUP BY DATETIME) subquery1;";

  // 같은 범주에 들어가는 장비 별 배열 선언
$PGW_IPv4_Traffic=array();
$PGW_IPv4_Session=array();
$PGW_IPv6_Traffic=array();
$PGW_IPv6_Session=array();

$PGW_Volte_Session=array();

$SGW_Traffic=array();
$SGW_Session=array();

$SMF_Session=array();
$UPF_Traffic=array();

$UPF_IMS_Session=array();

  // mysql 접속
$conn = mysqli_connect(
  '***',
  '***',
  '***',
  'MACA_RAW');

  
  // 각 장비 별 트래픽, 세션 data를 파싱하여 최고 부하를 계산하고 엑셀 및 배열에 저장
$result = mysqli_query($conn, $PGW01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/14.4*100,2);

$result2 = mysqli_query($conn, $PGW01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1000000*100,2);


$sheetIndex ->setCellValue('A3', 'GURO_PGW01');
$sheetIndex ->setCellValue('B3', '14.4 Gbps / 1,000,000 SESSION ');
$sheetIndex ->setCellValue('C3', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D3', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#1'] = $LOAD;
$PGW_IPv4_Session['PGW#1'] = $SLOAD;

$result = mysqli_query($conn, $PGW03_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/14.4*100,2);

$result2 = mysqli_query($conn, $PGW03_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1000000*100,2);

$sheetIndex ->setCellValue('A4', 'GURO_PGW03');
$sheetIndex ->setCellValue('B4', '14.4 Gbps / 1,000,000 SESSION ');
$sheetIndex ->setCellValue('C4', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D4', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#3'] = $LOAD;
$PGW_IPv4_Session['PGW#3'] = $SLOAD;


$result = mysqli_query($conn, $PGW04_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/14.4*100,2);

$result2 = mysqli_query($conn, $PGW04_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1000000*100,2);

$sheetIndex ->setCellValue('A5', 'GURO_PGW04');
$sheetIndex ->setCellValue('B5', '14.4 Gbps / 1,000,000 SESSION ');
$sheetIndex ->setCellValue('C5', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D5', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#4'] = $LOAD;
$PGW_IPv6_Session['PGW#4'] = $SLOAD;


$result = mysqli_query($conn, $PGW05_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/9*100,2);

$result2 = mysqli_query($conn, $PGW05_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/700000*100,2);

$sheetIndex ->setCellValue('A6', 'GURO_PGW05');
$sheetIndex ->setCellValue('B6', '9 Gbps / 700,000 SESSION ');
$sheetIndex ->setCellValue('C6', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D6', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#5'] = $LOAD;
$PGW_IPv6_Session['PGW#5'] = $SLOAD;


$result = mysqli_query($conn, $PGW11_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW11_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A7', $row['SYSTEM']);
$sheetIndex ->setCellValue('B7', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C7', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D7', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#11'] = $LOAD;
$PGW_IPv4_Session['PGW#11'] = $SLOAD;


$result = mysqli_query($conn, $PGW12_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW12_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A8', $row['SYSTEM']);
$sheetIndex ->setCellValue('B8', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C8', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D8', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#12'] = $LOAD;
$PGW_IPv4_Session['PGW#12'] = $SLOAD;


$result = mysqli_query($conn, $PGW13_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW13_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF+SESSSTAT_BEARACT_DED)']/4000000*100,2);

$sheetIndex ->setCellValue('A9', $row['SYSTEM']);
$sheetIndex ->setCellValue('B9', '43 Gbps / 4,000,000 SESSION ');
$sheetIndex ->setCellValue('C9', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D9', number_format($row2['MAX(SESSSTAT_BEARACT_DEF+SESSSTAT_BEARACT_DED)']).' SESS ('.$SLOAD.'%)');
$PGW_Volte_Session['PGW#13'] = $SLOAD;


$result = mysqli_query($conn, $PGW15_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW15_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A10', $row['SYSTEM']);
$sheetIndex ->setCellValue('B10', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C10', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D10', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#15'] = $LOAD;
$PGW_IPv4_Session['PGW#15'] = $SLOAD;


$result = mysqli_query($conn, $PGW16_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW16_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A11', $row['SYSTEM']);
$sheetIndex ->setCellValue('B11', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C11', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D11', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#16'] = $LOAD;
$PGW_IPv6_Session['PGW#16'] = $SLOAD;


$result = mysqli_query($conn, $PGW17_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW17_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A12', $row['SYSTEM']);
$sheetIndex ->setCellValue('B12', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C12', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D12', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#17'] = $LOAD;
$PGW_IPv6_Session['PGW#17'] = $SLOAD;


$result = mysqli_query($conn, $PGW18_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW18_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A13', $row['SYSTEM']);
$sheetIndex ->setCellValue('B13', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C13', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D13', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#18'] = $LOAD;
$PGW_IPv6_Session['PGW#18'] = $SLOAD;


$result = mysqli_query($conn, $PGW19_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW19_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A14', $row['SYSTEM']);
$sheetIndex ->setCellValue('B14', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C14', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D14', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv6_Traffic['PGW#19'] = $LOAD;
$PGW_IPv6_Session['PGW#19'] = $SLOAD;


$result = mysqli_query($conn, $PGW20_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/43*100,2);

$result2 = mysqli_query($conn, $PGW20_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_BEARACT_DEF)']/1800000*100,2);

$sheetIndex ->setCellValue('A15', $row['SYSTEM']);
$sheetIndex ->setCellValue('B15', '43 Gbps / 1,800,000 SESSION ');
$sheetIndex ->setCellValue('C15', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D15', number_format($row2['MAX(SESSSTAT_BEARACT_DEF)']).' SESS ('.$SLOAD.'%)');
$PGW_IPv4_Traffic['PGW#20'] = $LOAD;
$PGW_IPv4_Session['PGW#20'] = $SLOAD;

/* 철거 장비
$result = mysqli_query($conn, $SGW01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/28*100,2);

$result2 = mysqli_query($conn, $SGW01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/1500000*100,2);

$sheetIndex ->setCellValue('A16', $row['SYSTEM']);
$sheetIndex ->setCellValue('B16', '28 Gbps / 1,500,000 SESSION ');
$sheetIndex ->setCellValue('C16', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D16', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#1'] = $LOAD;
$SGW_Session['SGW#1'] = $SLOAD;


$result = mysqli_query($conn, $SGW02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/28*100,2);

$result2 = mysqli_query($conn, $SGW02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/1500000*100,2);

$sheetIndex ->setCellValue('A17', $row['SYSTEM']);
$sheetIndex ->setCellValue('B17', '28 Gbps / 1,500,000 SESSION ');
$sheetIndex ->setCellValue('C17', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D17', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#2'] = $LOAD;
$SGW_Session['SGW#2'] = $SLOAD;
*/

$result = mysqli_query($conn, $SGW11_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/70*100,2);

$result2 = mysqli_query($conn, $SGW11_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/3750000*100,2);

$sheetIndex ->setCellValue('A16', $row['SYSTEM']);
$sheetIndex ->setCellValue('B16', '70 Gbps / 3,750,000 SESSION ');
$sheetIndex ->setCellValue('C16', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D16', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#11'] = $LOAD;
$SGW_Session['SGW#11'] = $SLOAD;


$result = mysqli_query($conn, $SGW12_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/70*100,2);

$result2 = mysqli_query($conn, $SGW12_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/3750000*100,2);

$sheetIndex ->setCellValue('A17', $row['SYSTEM']);
$sheetIndex ->setCellValue('B17', '70 Gbps / 3,750,000 SESSION ');
$sheetIndex ->setCellValue('C17', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D17', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#12'] = $LOAD;
$SGW_Session['SGW#12'] = $SLOAD;

$result = mysqli_query($conn, $SGW13_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/70*100,2);

$result2 = mysqli_query($conn, $SGW13_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/3750000*100,2);

$sheetIndex ->setCellValue('A18', $row['SYSTEM']);
$sheetIndex ->setCellValue('B18', '70 Gbps / 3,750,000 SESSION ');
$sheetIndex ->setCellValue('C18', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D18', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#13'] = $LOAD;
$SGW_Session['SGW#13'] = $SLOAD;


$result = mysqli_query($conn, $SGW14_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/70*100,2);

$result2 = mysqli_query($conn, $SGW14_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/3750000*100,2);

$sheetIndex ->setCellValue('A19', $row['SYSTEM']);
$sheetIndex ->setCellValue('B19', '70 Gbps / 3,750,000 SESSION ');
$sheetIndex ->setCellValue('C19', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D19', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#14'] = $LOAD;
$SGW_Session['SGW#14'] = $SLOAD;


$result = mysqli_query($conn, $SGW15_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/70*100,2);

$result2 = mysqli_query($conn, $SGW15_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/3750000*100,2);

$sheetIndex ->setCellValue('A20', $row['SYSTEM']);
$sheetIndex ->setCellValue('B20', '70 Gbps / 3,750,000 SESSION ');
$sheetIndex ->setCellValue('C20', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D20', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SGW_Traffic['SGW#15'] = $LOAD;
$SGW_Session['SGW#15'] = $SLOAD;


$result = mysqli_query($conn, $UPF02_01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A21', $row['SYSTEM']);
$sheetIndex ->setCellValue('B21', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C21', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D21', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_01'] = $LOAD;


$result = mysqli_query($conn, $UPF02_02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A22', $row['SYSTEM']);
$sheetIndex ->setCellValue('B22', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C22', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D22', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_02'] = $LOAD;


$result = mysqli_query($conn, $UPF02_03_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_03_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A23', $row['SYSTEM']);
$sheetIndex ->setCellValue('B23', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C23', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D23', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_03'] = $LOAD;


$result = mysqli_query($conn, $UPF02_04_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_04_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A24', $row['SYSTEM']);
$sheetIndex ->setCellValue('B24', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C24', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D24', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_04'] = $LOAD;

$result = mysqli_query($conn, $UPF02_05_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_05_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A25', $row['SYSTEM']);
$sheetIndex ->setCellValue('B25', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C25', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D25', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_05'] = $LOAD;

$result = mysqli_query($conn, $UPF02_06_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_06_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A26', $row['SYSTEM']);
$sheetIndex ->setCellValue('B26', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C26', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D26', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_06'] = $LOAD;


$result = mysqli_query($conn, $UPF02_07_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_07_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A27', $row['SYSTEM']);
$sheetIndex ->setCellValue('B27', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C27', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D27', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_07'] = $LOAD;


$result = mysqli_query($conn, $UPF02_08_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_08_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A28', $row['SYSTEM']);
$sheetIndex ->setCellValue('B28', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C28', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D28', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_08'] = $LOAD;

$result = mysqli_query($conn, $UPF02_09_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_09_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A29', $row['SYSTEM']);
$sheetIndex ->setCellValue('B29', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C29', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D29', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_09'] = $LOAD;

$result = mysqli_query($conn, $UPF02_10_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_10_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A30', $row['SYSTEM']);
$sheetIndex ->setCellValue('B30', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C30', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D30', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_10'] = $LOAD;

$result = mysqli_query($conn, $UPF02_11_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_11_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A31', $row['SYSTEM']);
$sheetIndex ->setCellValue('B31', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C31', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D31', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_11'] = $LOAD;

$result = mysqli_query($conn, $UPF02_12_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF02_12_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A32', $row['SYSTEM']);
$sheetIndex ->setCellValue('B32', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C32', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D32', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_Traffic['UPF#02_12'] = $LOAD;


$result = mysqli_query($conn, $UPF11_01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A33', $row['SYSTEM']);
$sheetIndex ->setCellValue('B33', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C33', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D33', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_01'] = $LOAD;

$result = mysqli_query($conn, $UPF11_02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A34', $row['SYSTEM']);
$sheetIndex ->setCellValue('B34', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C34', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D34', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_02'] = $LOAD;

$result = mysqli_query($conn, $UPF11_03_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_03_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A35', $row['SYSTEM']);
$sheetIndex ->setCellValue('B35', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C35', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D35', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_03'] = $LOAD;

$result = mysqli_query($conn, $UPF11_04_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_04_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A36', $row['SYSTEM']);
$sheetIndex ->setCellValue('B36', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C36', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D36', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_04'] = $LOAD;


$result = mysqli_query($conn, $UPF11_05_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_05_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A37', $row['SYSTEM']);
$sheetIndex ->setCellValue('B37', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C37', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D37', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_05'] = $LOAD;

$result = mysqli_query($conn, $UPF11_06_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_06_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A38', $row['SYSTEM']);
$sheetIndex ->setCellValue('B38', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C38', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D38', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_06'] = $LOAD;


$result = mysqli_query($conn, $UPF11_07_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_07_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A39', $row['SYSTEM']);
$sheetIndex ->setCellValue('B39', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C39', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D39', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_07'] = $LOAD;


$result = mysqli_query($conn, $UPF11_08_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF11_08_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A40', $row['SYSTEM']);
$sheetIndex ->setCellValue('B40', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C40', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D40', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#11_08'] = $LOAD;

$result = mysqli_query($conn, $UPF12_01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A41', $row['SYSTEM']);
$sheetIndex ->setCellValue('B41', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C41', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D41', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_01'] = $LOAD;

$result = mysqli_query($conn, $UPF12_02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A42', $row['SYSTEM']);
$sheetIndex ->setCellValue('B42', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C42', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D42', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_02'] = $LOAD;

$result = mysqli_query($conn, $UPF12_03_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_03_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A43', $row['SYSTEM']);
$sheetIndex ->setCellValue('B43', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C43', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D43', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_03'] = $LOAD;

$result = mysqli_query($conn, $UPF12_04_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_04_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A44', $row['SYSTEM']);
$sheetIndex ->setCellValue('B44', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C44', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D44', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_04'] = $LOAD;


$result = mysqli_query($conn, $UPF12_05_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_05_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A45', $row['SYSTEM']);
$sheetIndex ->setCellValue('B45', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C45', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D45', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_05'] = $LOAD;

$result = mysqli_query($conn, $UPF12_06_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_06_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A46', $row['SYSTEM']);
$sheetIndex ->setCellValue('B46', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C46', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D46', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_06'] = $LOAD;


$result = mysqli_query($conn, $UPF12_07_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_07_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A47', $row['SYSTEM']);
$sheetIndex ->setCellValue('B47', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C47', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D47', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_07'] = $LOAD;


$result = mysqli_query($conn, $UPF12_08_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_08_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A48', $row['SYSTEM']);
$sheetIndex ->setCellValue('B48', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C48', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D48', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_08'] = $LOAD;

$result = mysqli_query($conn, $UPF12_09_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_09_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A49', $row['SYSTEM']);
$sheetIndex ->setCellValue('B49', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C49', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D49', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_09'] = $LOAD;

$result = mysqli_query($conn, $UPF12_10_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_10_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A50', $row['SYSTEM']);
$sheetIndex ->setCellValue('B50', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C50', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D50', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_10'] = $LOAD;

$result = mysqli_query($conn, $UPF12_11_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_11_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A51', $row['SYSTEM']);
$sheetIndex ->setCellValue('B51', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C51', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D51', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_11'] = $LOAD;

$result = mysqli_query($conn, $UPF12_12_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF12_12_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A52', $row['SYSTEM']);
$sheetIndex ->setCellValue('B52', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C52', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D52', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#12_12'] = $LOAD;

$result = mysqli_query($conn, $UPF13_01_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_01_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A53', $row['SYSTEM']);
$sheetIndex ->setCellValue('B53', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C53', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D53', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_01'] = $LOAD;

$result = mysqli_query($conn, $UPF13_02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A54', $row['SYSTEM']);
$sheetIndex ->setCellValue('B54', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C54', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D54', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_02'] = $LOAD;

$result = mysqli_query($conn, $UPF13_03_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_03_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A55', $row['SYSTEM']);
$sheetIndex ->setCellValue('B55', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C55', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D55', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_03'] = $LOAD;

$result = mysqli_query($conn, $UPF13_04_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_04_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A56', $row['SYSTEM']);
$sheetIndex ->setCellValue('B56', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C56', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D56', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_04'] = $LOAD;


$result = mysqli_query($conn, $UPF13_05_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_05_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A57', $row['SYSTEM']);
$sheetIndex ->setCellValue('B57', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C57', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D57', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_05'] = $LOAD;

$result = mysqli_query($conn, $UPF13_06_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_06_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A58', $row['SYSTEM']);
$sheetIndex ->setCellValue('B58', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C58', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D58', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_06'] = $LOAD;


$result = mysqli_query($conn, $UPF13_07_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_07_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A59', $row['SYSTEM']);
$sheetIndex ->setCellValue('B59', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C59', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D59', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_07'] = $LOAD;


$result = mysqli_query($conn, $UPF13_08_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_08_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A60', $row['SYSTEM']);
$sheetIndex ->setCellValue('B60', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C60', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D60', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_08'] = $LOAD;

$result = mysqli_query($conn, $UPF13_09_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_09_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A61', $row['SYSTEM']);
$sheetIndex ->setCellValue('B61', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C61', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D61', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_09'] = $LOAD;

$result = mysqli_query($conn, $UPF13_10_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_10_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A62', $row['SYSTEM']);
$sheetIndex ->setCellValue('B62', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C62', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D62', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_10'] = $LOAD;

$result = mysqli_query($conn, $UPF13_11_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_11_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A63', $row['SYSTEM']);
$sheetIndex ->setCellValue('B63', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C63', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D63', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_11'] = $LOAD;

$result = mysqli_query($conn, $UPF13_12_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/30*100,2);

$result2 = mysqli_query($conn, $UPF13_12_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(CURRENT_SESSION)']/1200000*100,2);

$sheetIndex ->setCellValue('A64', $row['SYSTEM']);
$sheetIndex ->setCellValue('B64', '30 Gbps / 1,200,000 SESSION ');
$sheetIndex ->setCellValue('C64', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D64', number_format($row2['MAX(CURRENT_SESSION)']).' SESS ('.$SLOAD.'%)');
$UPF_IMS_Session['UPF#13_12'] = $LOAD;


$result = mysqli_query($conn, $SMF02_TRAFFIC);
$row = mysqli_fetch_array($result);
$TEMP = $row['MAX(subquery1.RX)']/1000;
$LOAD = round($TEMP/10*100,2);

$result2 = mysqli_query($conn, $SMF02_SESSION);
$row2 = mysqli_fetch_array($result2);
$SLOAD = round($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']/2000000*100,2);

$sheetIndex ->setCellValue('A65', $row['SYSTEM']);
$sheetIndex ->setCellValue('B65', '10 Gbps / 2,000,000 SESSION ');
$sheetIndex ->setCellValue('C65', $TEMP.' Gbps ('.$LOAD.'%)');
$sheetIndex ->setCellValue('D65', number_format($row2['MAX(SESSSTAT_TOTCUR_BEARERS)']).' SESS ('.$SLOAD.'%)');
$SMF_Session['SMF#2'] = $SLOAD;




$objPHPExcel->getActiveSheet()->getStyle("A1:E65")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(35);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(20);

$TD_COLOR = array(

    //배경색 설정
    'fill' => array(
     'type' => PHPExcel_Style_Fill::FILL_SOLID,
     'color' => array('rgb'=>'888888'),
    ),

    //글자색 설정
    'font' => array(
     'bold' => 'true',
     'size' => '12',
     'color' => array('rgb'=>'FFFFFF')
    ),

    //테두리 설정
    'borders' => array(
     'allborders' => array(
      'style' => PHPExcel_Style_Border::BORDER_THIN,
      'color' => array('argb'=>'000000')
     )
    ),

);

$objPHPExcel->getActiveSheet()->getStyle("A2:E2")->applyFromArray($TD_COLOR);

$TD_COLOR2 = array(

    //배경색 설정
    'fill' => array(
     'type' => PHPExcel_Style_Fill::FILL_SOLID,
     'color' => array('rgb'=>'FFFFFF'),
    ),

    //글자색 설정
    'font' => array(
     'bold' => 'true',
     'size' => '12',
     'color' => array('rgb'=>'000000')
    ),

    //테두리 설정
    'borders' => array(
     'allborders' => array(
      'style' => PHPExcel_Style_Border::BORDER_THIN,
      'color' => array('argb'=>'000000')
     )
    ),
);


$objPHPExcel->getActiveSheet()->getStyle("A3:E65")->applyFromArray($TD_COLOR2);


$myWorkSheet = new PHPExcel_Worksheet($objPHPExcel, 'Summary');
$objPHPExcel->addSheet($myWorkSheet, 0);

$sheetIndex2 = $objPHPExcel->setActiveSheetIndex(0);
$sheet = $objPHPExcel->getActiveSheet();

$sheetIndex2->mergeCells('A1:G1');
$sheetIndex2->mergeCells('A3:A9');
$sheetIndex2->mergeCells('A10:A12');
$sheetIndex2->mergeCells('B3:B4');
$sheetIndex2->mergeCells('B5:B6');
$sheetIndex2->mergeCells('B8:B9');
$sheetIndex2->mergeCells('C3:C4');
$sheetIndex2->mergeCells('C5:C6');
$sheetIndex2->mergeCells('C8:C9');

$sheetIndex2->getStyle('A1')->getFont()->setSize(15)->setBold(true);

  // 같은 범주에 있는 장비 중 가장 높은 부하율을 가지는 장비 요약 시트 생성
$sheetIndex2->setCellValue('A1','ㅇ 호처리(시스코)');

$sheetIndex2->setCellValue('A2','구분');
$sheetIndex2->setCellValue('B2','시스템');
$sheetIndex2->setCellValue('C2','시설 수');
$sheetIndex2->setCellValue('D2','부하기준');
$sheetIndex2->setCellValue('E2','최고부하');
$sheetIndex2->setCellValue('F2','부하율');
$sheetIndex2->setCellValue('G2','비고');

$sheetIndex2->setCellValue('A3','LTE');
$sheetIndex2->setCellValue('A10','5G');

$sheetIndex2->setCellValue('B3','PGW(IPv6)');
$sheetIndex2->setCellValue('B5','PGW(IPv4)');
$sheetIndex2->setCellValue('B7','PGW(VoLTE)');
$sheetIndex2->setCellValue('B8','SGW');
$sheetIndex2->setCellValue('B10','SMF');
$sheetIndex2->setCellValue('B11','UPF(DATA)');
$sheetIndex2->setCellValue('B12','UPF(IMS)');

$sheetIndex2->setCellValue('D3','트래픽');
$sheetIndex2->setCellValue('D4','세션수');
$sheetIndex2->setCellValue('D5','트래픽');
$sheetIndex2->setCellValue('D6','세션수');
$sheetIndex2->setCellValue('D7','세션수');
$sheetIndex2->setCellValue('D8','트래픽');
$sheetIndex2->setCellValue('D9','세션수');
$sheetIndex2->setCellValue('D10','세션수');
$sheetIndex2->setCellValue('D11','트래픽');
$sheetIndex2->setCellValue('D12','세션수');


$objPHPExcel->getActiveSheet()->getStyle('G3')->getAlignment()->setWrapText(true);
$sheetIndex2->setCellValue('G3','소용량 : 14.4G, 대용량 : 43G');
$sheetIndex2->setCellValue('G4','소용량 : 100 만, 대용량 : 180 만');
$sheetIndex2->setCellValue('G5','소용량 : 14.4G, 대용량 : 43G');
$sheetIndex2->setCellValue('G6','소용량 : 100 만, 대용량 : 180 만');
$sheetIndex2->setCellValue('G7','400 만');
$sheetIndex2->setCellValue('G8','소용량 : 28G, 대용량 : 70G');
$sheetIndex2->setCellValue('G9','소용량 : 150 만, 대용량 : 375 만');
$sheetIndex2->setCellValue('G10','200 만');
$sheetIndex2->setCellValue('G11','10G');
$sheetIndex2->setCellValue('G12','120 만');

$TD_COLOR3 = array(

    //배경색 설정
    'fill' => array(
     'type' => PHPExcel_Style_Fill::FILL_SOLID,
     'color' => array('rgb'=>'FFFFFF'),
    ),

    //글자색 설정
    'font' => array(
     'size' => '12',
     'color' => array('rgb'=>'000000')
    ),

    //테두리 설정
    'borders' => array(
     'allborders' => array(
      'style' => PHPExcel_Style_Border::BORDER_THIN,
      'color' => array('argb'=>'000000')
     )
    ),
);

$TD_COLOR4 = array(

    //배경색 설정
    'fill' => array(
     'type' => PHPExcel_Style_Fill::FILL_SOLID,
     'color' => array('rgb'=>'FFFFFF'),
    ),

    //글자색 설정
    'font' => array(
     'bold' => 'true',
     'size' => '12',
     'color' => array('rgb'=>'FF0000')
    ),

    //테두리 설정
    'borders' => array(
     'allborders' => array(
      'style' => PHPExcel_Style_Border::BORDER_THIN,
      'color' => array('argb'=>'000000')
     )
    ),
);

$objPHPExcel->getActiveSheet()->getStyle("A2:G2")->applyFromArray($TD_COLOR);
$objPHPExcel->getActiveSheet()->getStyle("A3:G12")->applyFromArray($TD_COLOR3);

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(35);


$objPHPExcel->getActiveSheet()->getStyle("A2:G12")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPExcel->getActiveSheet()->getStyle("A2:G12")->getAlignment ()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

// 배열을 이용하여 data 표기
$sheetIndex2->setCellValue('C3',count($PGW_IPv6_Traffic));
$sheetIndex2->setCellValue('C5',count($PGW_IPv4_Traffic));
$sheetIndex2->setCellValue('C7',count($PGW_Volte_Session));
$sheetIndex2->setCellValue('C8',count($SGW_Session));
$sheetIndex2->setCellValue('C10',count($SMF_Session));
$sheetIndex2->setCellValue('C11',count($UPF_Traffic));
$sheetIndex2->setCellValue('C12',count($UPF_IMS_Session));

$sheetIndex2->setCellValue('E3',array_search(max($PGW_IPv6_Traffic),$PGW_IPv6_Traffic));
$sheetIndex2->setCellValue('E4',array_search(max($PGW_IPv6_Session),$PGW_IPv6_Session));
$sheetIndex2->setCellValue('E5',array_search(max($PGW_IPv4_Traffic),$PGW_IPv4_Traffic));
$sheetIndex2->setCellValue('E6',array_search(max($PGW_IPv4_Session),$PGW_IPv4_Session));
$sheetIndex2->setCellValue('E7',array_search(max($PGW_Volte_Session),$PGW_Volte_Session));
$sheetIndex2->setCellValue('E8',array_search(max($SGW_Traffic),$SGW_Traffic));
$sheetIndex2->setCellValue('E9',array_search(max($SGW_Session),$SGW_Session));
$sheetIndex2->setCellValue('E10',array_search(max($SMF_Session),$SMF_Session));
$sheetIndex2->setCellValue('E11',array_search(max($UPF_Traffic),$UPF_Traffic));
$sheetIndex2->setCellValue('E12',array_search(max($UPF_IMS_Session),$UPF_IMS_Session));


$sheetIndex2->setCellValue('F3',max($PGW_IPv6_Traffic).'%');
$sheetIndex2->setCellValue('F4',max($PGW_IPv6_Session).'%');
$sheetIndex2->setCellValue('F5',max($PGW_IPv4_Traffic).'%');
$sheetIndex2->setCellValue('F6',max($PGW_IPv4_Session).'%');
$sheetIndex2->setCellValue('F7',max($PGW_Volte_Session).'%');
$sheetIndex2->setCellValue('F8',max($SGW_Traffic).'%');
$sheetIndex2->setCellValue('F9',max($SGW_Session).'%');
$sheetIndex2->setCellValue('F10',max($SMF_Session).'%');
$sheetIndex2->setCellValue('F11',max($UPF_Traffic).'%');
$sheetIndex2->setCellValue('F12',max($UPF_IMS_Session).'%');

  // 부하가 80% 이상일 경우 색상 표시
if(max($PGW_IPv6_Traffic)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F3")->applyFromArray($TD_COLOR4);
}
if(max($PGW_IPv6_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F4")->applyFromArray($TD_COLOR4);
}
if(max($PGW_IPv4_Traffic)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F5")->applyFromArray($TD_COLOR4);
}
if(max($PGW_IPv4_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F6")->applyFromArray($TD_COLOR4);
}
if(max($PGW_Volte_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F7")->applyFromArray($TD_COLOR4);
}
if(max($SGW_Traffic)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F8")->applyFromArray($TD_COLOR4);
}
if(max($SGW_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F9")->applyFromArray($TD_COLOR4);
}
if(max($SMF_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F10")->applyFromArray($TD_COLOR4);
}
if(max($UPF_Traffic)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F11")->applyFromArray($TD_COLOR4);
}
if(max($UPF_IMS_Session)>=80)
{
        $objPHPExcel->getActiveSheet()->getStyle("F12")->applyFromArray($TD_COLOR4);
}


mysqli_close($conn);

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename='.$STARTDATE.'___'.$ENDDATE.'___'.$STAT.'(시스코).xls');
header('Cache-Control: max-age=0');
 
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save('php://output');
 
exit;

}

?>
